-- ============================================
-- FAESMA - Documentação: Mapeamento course_curriculum
-- ============================================
-- Mapeamento entre view remota disciplinas_curso_site e tabela local course_curriculum
-- Versão: 1.1
-- ============================================

-- ============================================
-- ESTRUTURA DA VIEW REMOTA: disciplinas_curso_site
-- ============================================
-- Campo              | Tipo           | Descrição
-- -------------------|----------------|------------------------------------------
-- disciplina_nome    | varchar(150)   | Nome da disciplina
-- id                 | varchar(100)   | ID do curso remoto (= cod_externo local)
-- curso_nome         | varchar(255)   | Nome do curso
-- cod_externo        | varchar(15)    | Código externo/sigla do curso (ex: "RH")
-- carga_horaria      | float          | Carga horária da disciplina
-- duracao            | varchar(100)   | Duração do curso (ex: "2 anos | 1.600 horas")
-- modalidade         | varchar(255)   | Modalidade do curso -> course_modalities.nome
-- modulo             | varchar(255)   | Módulo/Semestre (ex: "Modulo 1", "Modulo 2")

-- ============================================
-- ESTRUTURA DA TABELA LOCAL: course_curriculum
-- ============================================
-- Campo              | Tipo           | Descrição
-- -------------------|----------------|------------------------------------------
-- id                 | INT AUTO_INC   | ID local (chave primária)
-- course_id          | INT            | FK para courses.id
-- semestre           | INT            | Número do semestre/módulo
-- disciplina         | VARCHAR(200)   | Nome da disciplina
-- carga_horaria      | INT            | Carga horária da disciplina
-- ementa             | TEXT           | Ementa da disciplina (não na view)
-- ordem              | INT            | Ordem de exibição
-- created_at         | TIMESTAMP      | Data de criação
-- updated_at         | TIMESTAMP      | Data de atualização

-- ============================================
-- TABELA RELACIONADA: course_modalities
-- ============================================
-- A modalidade da view remota corresponde à tabela course_modalities:
-- - view.modalidade (ex: "EAD") -> course_modalities.nome
-- - O curso (courses) tem modality_id que referencia course_modalities.id
-- - Assim, a modalidade é obtida via: courses.modality_id -> course_modalities

-- ============================================
-- MAPEAMENTO DE CAMPOS
-- ============================================
-- View Remota              => Tabela Local
-- ----------------------------|------------------
-- disciplina_nome             => disciplina
-- carga_horaria               => carga_horaria
-- modulo                      => semestre (convertido: "Modulo 1" -> 1)
-- id (ID do curso remoto)     => usado para encontrar course_id via courses.cod_externo
-- modalidade                  => course_modalities.nome (via courses.modality_id)

-- Campos NÃO mapeados diretamente (informativos apenas):
-- - cod_externo (sigla do curso)
-- - curso_nome (nome do curso)
-- - duracao (duração do curso)

-- ============================================
-- LÓGICA DE SINCRONIZAÇÃO
-- ============================================
-- 1. Busca disciplinas da view remota agrupadas por 'id' (ID do curso)
-- 2. Para cada grupo, encontra o curso local via courses.cod_externo = view.id
-- 3. Para cada disciplina:
--    a. Gera chave única: MD5(disciplina_lower + semestre)
--    b. Se existe: UPDATE
--    c. Se não existe: INSERT
-- 4. Remove disciplinas locais que não existem mais na view
